// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package container

import (
	"github.com/Cliengo/acelle-mail/container/logger"
	"github.com/Cliengo/acelle-mail/infrastructure/http"
	"github.com/Cliengo/acelle-mail/infrastructure/listener"
	"github.com/Cliengo/acelle-mail/repository"
	"github.com/Cliengo/acelle-mail/repository/mongo"
	"github.com/Cliengo/acelle-mail/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewServer() (http.Server, error) {
	healthHandler := http.NewHealthHandler()
	loggerLogger := logger.GetLogger()
	client, err := mongo.New()
	if err != nil {
		return http.Server{}, err
	}
	integrationRepository := mongo.NewMongoIntegrationRepository(client)
	acelleMailService := services.NewAcelleMailService(loggerLogger)
	accountService := services.NewAccountService(loggerLogger, integrationRepository, acelleMailService)
	integrationHandler := http.NewIntegrationHandler(loggerLogger, accountService, acelleMailService)
	handlers := http.NewServerHandlers(healthHandler, integrationHandler)
	server := http.New(handlers)
	return server, nil
}

func NewListener() (listener.StreamsListener, error) {
	loggerLogger := logger.GetLogger()
	client, err := mongo.New()
	if err != nil {
		return listener.StreamsListener{}, err
	}
	watcherRepository := mongo.NewMongoWatcherRepository(client)
	integrationRepository := mongo.NewMongoIntegrationRepository(client)
	acelleMailService := services.NewAcelleMailService(loggerLogger)
	streamsService := services.NewStreamService(loggerLogger, integrationRepository, acelleMailService)
	streamsListener := listener.New(loggerLogger, watcherRepository, streamsService)
	return streamsListener, nil
}

// wire.go:

var repositorySet = wire.NewSet(mongo.New, mongo.NewMongoIntegrationRepository, wire.Bind(new(repository.IntegrationRepository), new(mongo.IntegrationRepository)), mongo.NewMongoWatcherRepository, wire.Bind(new(repository.StreamWatcherRepository), new(mongo.WatcherRepository)))

var servicesSet = wire.NewSet(services.NewAcelleMailService, services.NewAccountService, services.NewStreamService)

var handlerSet = wire.NewSet(http.NewHealthHandler, http.NewIntegrationHandler, http.NewServerHandlers)
