version: '3.9'

services:
  server:
    build:
      context: .
    command: "server"
    ports:
      - "8080:8080"
    container_name: server
  listener:
    build:
      context: .
    command: "listener"
    container_name: listener